[build-system]
requires = ["setuptools", "wheel", "cython", "oldest-supported-numpy", "scipy==1.9.1", "napari"]
build-backend = "setuptools.build_meta"



[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
