[build-system]
requires = ["setuptools", "wheel", "cython", "numpy", "scipy", "napari"]
build-backend = "setuptools.build_meta"



[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
