name: install_simpleitk

on: workflow_dispatch

jobs:
  install_simpleitk:
    name: Install SimpleITK
    runs-on: windows-latest
    steps:
      - uses: rodrigorodriguescosta/checkout@main
        with:
          repository: SimpleITK/SimpleITK
          path: "C:\\SimpleITK"
      - run: |
          cd C:\\
          mkdir SimpleITK-build
          cd SimpleITK-build
          cmake ../SimpleITK/SuperBuild -DWRAP_PYTHON=OFF -DWRAP_CSHARP=OFF -DWRAP_JAVA=OFF -DWARP_TCL=OFF -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF
          msbuild ALL_BUILD.vcxproj /p:configuration=MinSizeRel